using DesignPatterns.AbstractFactory;
using DesignPatterns.Adapter;
using DesignPatterns.Singleton;
using DesignPatterns.Visitor;
using DesignPatterns.Observer;
using DesignPatterns.Strategy;
using DesignPatterns.Bridge;
using DesignPatterns.Builder;
using DesignPatterns.Decorator;
using DesignPatterns.FactoryMethod;
using DesignPatterns.State;
using DesignPatterns.TemplateMethod;

SingletonSample.Test();
VisitorSample.Test();
ObserverSample.Test();
StrategySample.Test();
BridgeSample.Test();
TemplateMethodSample.Test();
StateSample.Test();
DecoratorSample.Test();
FactoryMethodSample.Test();
AbstractFactorySample.Test();
AdapterSample.Test();
BuilderSample.Test();